function audit_final_fe_budgets
%AUDIT_FINAL_FE_BUDGETS Verify observed FE counts in all final campaigns.

codeDir = fileparts(mfilename('fullpath'));
packageDir = fileparts(codeDir);
resultsDir = fullfile(packageDir, 'results');
reportPath = fullfile(packageDir, 'documentation', ...
    'FE_BUDGET_AUDIT.txt');

if exist(reportPath, 'file')
    delete(reportPath);
end
diary(reportPath);
cleanupDiary = onCleanup(@() diary('off')); %#ok<NASGU>

campaigns = [
    campaign_info( ...
        "CEC2022 sensitivity", ...
        "CEC2022_sensitivity_common_seeds", ...
        "run_CEC2022_sensitivity_common_seeds.m", ...
        200000, "EstFEs", "RawEstFEs", 6120, "CEC")
    campaign_info( ...
        "CEC2022 ablation", ...
        "CEC2022_ablation_BC1_common_seeds", ...
        "run_CEC2022_ablation_BC1_common_seeds.m", ...
        200000, "EstFEs", "RawEstFEs", 2160, "CEC")
    campaign_info( ...
        "CEC2022 external", ...
        "CEC2022_external_BC1_common_seeds", ...
        "run_CEC2022_external_BC1_common_seeds.m", ...
        200000, "EstFEs", "RawEstFEs", 3600, "CEC")
    campaign_info( ...
        "FIR sensitivity", ...
        "FIR_sensitivity_common_seeds", ...
        "run_FIR_sensitivity_common_seeds.m", ...
        150000, "FEs", "FEAlg", 4080, "FIR")
    campaign_info( ...
        "FIR ablation", ...
        "FIR_ablation_AC1_common_seeds", ...
        "run_FIR_ablation_AC1_common_seeds.m", ...
        150000, "FEs", "FEAlg", 1440, "FIR")
    campaign_info( ...
        "FIR external", ...
        "FIR_external_AC1_common_seeds", ...
        "run_FIR_external_AC1_common_seeds.m", ...
        150000, "FEs", "FEAlg", 2400, "FIR")
];

fprintf('FINAL FUNCTION-EVALUATION BUDGET AUDIT\n');
fprintf('Generated: %s\n', string(datetime('now')));
fprintf('Required utilization: [99.5%%, 100%%] of the declared budget.\n\n');

totalTasks = 0;
globalMinimumUtilization = inf;
globalMaximumUtilization = -inf;

for c = 1:numel(campaigns)
    info = campaigns(c);
    campaignDir = fullfile(resultsDir, info.directory);
    csvPath = fullfile(campaignDir, 'csv', 'task_results.csv');
    matPath = fullfile(campaignDir, 'mat', 'final_workspace.mat');
    runnerPath = fullfile(codeDir, info.runner);

    assert(isfile(csvPath), 'Missing task CSV: %s', csvPath);
    assert(isfile(matPath), 'Missing final workspace: %s', matPath);
    assert(isfile(runnerPath), 'Missing runner: %s', runnerPath);

    T = readtable(csvPath, 'TextType', 'string', ...
        'VariableNamingRule', 'preserve');
    M = load(matPath, 'CFG', 'TaskResults', char(info.rawVariable));
    fe = T.(char(info.feColumn));
    matFe = M.TaskResults.(char(info.feColumn));
    rawFe = M.(char(info.rawVariable));

    assert(height(T) == info.expectedTasks, ...
        '%s has %d tasks; expected %d.', ...
        info.label, height(T), info.expectedTasks);
    assert(M.CFG.Max_FEs == info.budget, ...
        '%s declares Max_FEs=%g; expected %g.', ...
        info.label, M.CFG.Max_FEs, info.budget);
    assert(all(T.OK == 1), '%s contains failed tasks.', info.label);
    assert(all(isfinite(fe)), '%s contains nonfinite FE counts.', info.label);
    assert(all(fe <= info.budget), '%s exceeds its FE budget.', info.label);
    assert(all(fe >= 0.995 * info.budget), ...
        '%s uses less than 99.5%% of its FE budget.', info.label);
    assert(isequaln(fe, matFe), ...
        '%s CSV and MAT TaskResults FE columns differ.', info.label);
    assert(isequaln(sort(fe), sort(rawFe(:))), ...
        '%s raw FE array differs from TaskResults.', info.label);

    runnerText = fileread(runnerPath);
    if info.domain == "CEC"
        assert(contains(runnerText, ...
            'FE_COUNTER_CEC_REAL = FE_COUNTER_CEC_REAL + 1'), ...
            '%s does not increment the CEC objective-call counter.', info.label);
    else
        assert(contains(runnerText, ...
            'FE_COUNTER_FIR = FE_COUNTER_FIR + 1'), ...
            '%s does not increment the FIR objective-call counter.', info.label);
    end

    minimumUtilization = 100 * min(fe) / info.budget;
    maximumUtilization = 100 * max(fe) / info.budget;
    globalMinimumUtilization = min(globalMinimumUtilization, minimumUtilization);
    globalMaximumUtilization = max(globalMaximumUtilization, maximumUtilization);
    totalTasks = totalTasks + height(T);

    fprintf('%s: PASS\n', info.label);
    fprintf('  Budget: %d | tasks: %d | observed range: %d--%d\n', ...
        info.budget, height(T), min(fe), max(fe));
    fprintf('  Utilization range: %.4f%%--%.4f%%\n', ...
        minimumUtilization, maximumUtilization);

    aliases = unique(T.Alias, 'stable');
    for a = 1:numel(aliases)
        rows = T.Alias == aliases(a);
        fprintf('    %-12s %d--%d FEs (%.4f%%--%.4f%%)\n', ...
            aliases(a), min(fe(rows)), max(fe(rows)), ...
            100 * min(fe(rows)) / info.budget, ...
            100 * max(fe(rows)) / info.budget);
    end
    fprintf('\n');
end

assert(totalTasks == 19800, ...
    'Unexpected total task count: %d.', totalTasks);
fprintf('TOTAL TASKS: %d\n', totalTasks);
fprintf('GLOBAL UTILIZATION RANGE: %.4f%%--%.4f%%\n', ...
    globalMinimumUtilization, globalMaximumUtilization);
fprintf('FINAL STATUS: PASS\n');
fprintf(['All saved FE counts are observed, internally consistent, closely ' ...
    'matched, and within the declared budgets.\n']);
end

function info = campaign_info(label, directory, runner, budget, ...
    feColumn, rawVariable, expectedTasks, domain)
info = struct( ...
    'label', label, ...
    'directory', directory, ...
    'runner', runner, ...
    'budget', budget, ...
    'feColumn', feColumn, ...
    'rawVariable', rawVariable, ...
    'expectedTasks', expectedTasks, ...
    'domain', domain);
end
